/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package ccri.neighborhood.exercise;

public class App {
  public static void main(String[] args) {
    System.out.println("Please run \"gradle clean build\" to execute the neighborhood code. This " +
        "will execute tests and generate code quality reports.");
  }
}
